<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Carta Automatica</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
body {
	background-image:   url(images/fondo.gif);
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
-->
</style>
<link href="estilos.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<script src="Scripts/AC_RunActiveContent.js" type="text/javascript"></script>
<style type="text/css">
<!--
.style1 {color: #FFFFFF}
.txt_negro .txt_negro {
	color: #666;
}
.lal {
	font-size: 10px;
}
-->
</style>
<script type="text/javascript">

 

  var _gaq = _gaq || [];

  _gaq.push(['_setAccount', 'UA-42658052-1']);

  _gaq.push(['_setDomainName', 'cartaautomatica.com.ar']);

  _gaq.push(['_trackPageview']);

 

  (function() {

    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

  })();

 

</script>
<!-- google analytics code 02-06-2016 -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
 
  ga('create', 'UA-42658052-1', 'auto');
  ga('send', 'pageview');
 
</script>
<!-- end google analytics code -->
</head>

<body>
  <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WVX3DM"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WVX3DM');</script>
<!-- End Google Tag Manager -->
<table width="200" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <th valign="top" scope="col"> </th>
    <th scope="col"><table width="770" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td width="9" background="images/left.gif">&nbsp;</td>
        <td bgcolor="#FFFFFF"><table width="752" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="752" height="100">
              <param name="movie" value="images/top.swf">
              <param name="quality" value="high">
              <param name="wmode" value="opaque">
              <embed src="images/top.swf" quality="high" wmode="opaque" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="752" height="100"></embed>
            </object></td>
          </tr>
          <tr>
            <td><table width="752" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="190" valign="top"><!--#include file="inc_banners_left.asp" --></td>
                <td width="7" valign="top"></td>
                <td width="555" valign="top"><table width="555" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                     
                  </tr>
                  <tr>
                    <td valign="top"><table width="549" border="0" cellspacing="0" cellpadding="0">
                      <tr> </tr>
                      <tr>
                        <td></td>
                        <td></td>
                      </tr>
                      <tr>
                        <td width="1" height="1"></td>
                        <td width="547" valign="top"><table width="547" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td width="547" height="1" align="center" ></td>
                          </tr>
                          <tr>
                            <td align="center"><img src="images/tit_promociones.jpg" width="548" height="110"></td>
                          </tr>
                          <tr>
                            <td align="center"><img src="images/banner3-interior.jpg"></td>
                          </tr>
                          <tr>
                            <td align="left" class="gris2" id="bienvenida">&nbsp;</td>
                          </tr>
                          <tr>
                            <td align="left"><span class="gris2">13) AL SOLICITAR LA ADHESI&Oacute;N AL RESUMEN DIGITAL DE TARJETAS DE CR&Eacute;DITO CARTA MASTERCARD EMITIDAS POR CORDIAL, EL CLIENTE SOLICITA MODIFICAR EL SISTEMA DE ENV&Iacute;O POR CORREO POSTAL AL SISTEMA REMISI&Oacute;N POR CORREO ELECTR&Oacute;NICO, DEJANDO SIN EFECTO EL ENV&Iacute;O POR CORREO POSTAL. EL RESUMEN DIGITAL, ESTAR&Aacute; A DISPOSICI&Oacute;N DEL CLIENTE CON LA PERIODICIDAD ESTABLECIDA POR LAS NORMAS. CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. ORGANIZA LA PROMOCI&Oacute;N &ldquo;SORTEO LED TV E-RESUMEN&rdquo;. PROMOCION SIN OBLIGACION DE COMPRA. V&Aacute;LIDA EN LAS CIUDADES DE COMODORO RIVADAVIA, CALETA OLIVIA, CIPOLETTI, CUTRAL C&Oacute;, GRAL. ROCA, NEUQU&Eacute;N, PUERTO MADRYN, BAH&Iacute;A BLANCA, PUNTA ALTA, TRELEW, CHOELE CHOEL, VILLA REGINA, VIEDMA, R&Iacute;O GALLEGOS, TUCUM&Aacute;N, BARILOCHE, SANTA ROSA, LA PLATA Y R&Iacute;O GRANDE, ENTRE LAS 00 HS. DEL D&Iacute;A 1 DE OCTUBRE DE 2016 Y LAS 24 HS. DEL D&Iacute;A 31 DE DICIEMBRE DE 2016 INCLUSIVE. CONSULTE EN LOS LOCALES DE PARTICIPACI&Oacute;N. CONSULTAR BASES Y CONDICIONES EN WWW.CARTAAUTOMATICA.COM.AR Y EN LOS LOCALES DE PARTICIPACI&Oacute;N DE TARJETA AUTOM&Aacute;TICA S.A. SITOS EN EL &Aacute;MBITO DE PARTICIPACI&Oacute;N. LOS PREMIOS CONSISTIR&Aacute;N: (I) MES DE 10/2016: UN TELEVISOR LED DE 43 PULGADAS, MODELO 43PFG5501, MARCA PHILIPS; (II) MES DE 11/2016: UN TELEVISOR LED DE 43 PULGADAS, MODELO 43PFG5501, MARCA PHILIPS Y (III) MES DE 12/2016: UN TELEVISOR LED 43 PULGADAS, MODELO 43PFG5501, MARCA PHILIPS. NO PODR&Aacute;N PARTICIPAR EN LA PROMOCI&Oacute;N EL PERSONAL DE CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A., NI DEL GRUPO SUPERVIELLE S.A., NI DE NINGUNA DE LAS EMPRESAS QUE FORMAN PARTE INTEGRANTE DEL GRUPO SUPERVIELLE S.A., NI SUS AGENCIAS DE PUBLICIDAD Y/O PROMOCI&Oacute;N, NI TAMPOCO SUS FAMILIARES DIRECTOS HASTA EL SEGUNDO GRADO DE CONSANGUINIDAD DE LOS NOMBRADOS COMO AS&Iacute; TAMPOCO SUS FAMILIARES HASTA SEGUNDO GRADO. LAS IM&Aacute;GENES SON DE CAR&Aacute;CTER ILUSTRATIVO. 14) LA APLICACI&Oacute;N CARTA APP LA &ldquo;APLICACI&Oacute;N&rdquo; ES ADMINISTRADA CORDIAL. LA APLICACI&Oacute;N ESTAR&Aacute; DISPONIBLE PARA CLIENTES TITULARES DE TARJETAS DE CR&Eacute;DITO MASTERCARD CARTA AUTOM&Aacute;TICA EMITIDAS POR CORDIAL. DISPONIBLE PARA SMARTPHONES Y/O TABLETS CON SISTEMA OPERATIVO ANDROID. LA APLICACI&Oacute;N SE PODR&Aacute; BAJAR DE GOOGLE PLAY. LA APLICACI&Oacute;N NO REEMPLAZA LA EMISI&Oacute;N DEL RESUMEN MENSUAL EN LOS T&Eacute;RMINOS DEL ART. 23 DE LA LEY DE TARJETAS DE CR&Eacute;DITO. EL ACCESO A LA APLICACI&Oacute;N EST&Aacute; SUJETO A LOS T&Eacute;RMINOS Y CONDICIONES Y POL&Iacute;TICAS QUE REGULAN EL USO Y FUNCIONAMIENTO DE LA MISMA. PROMOCIONES NO ACUMULABLES NI COMBINABLES CON OTRAS VIGENTES.
</span></td>
                          </tr>
                          <tr>
                            <td align="left"><p>&nbsp;</p><p>&nbsp;</p> <p align="left" class="gris2"><strong><u>BASES PROMOCI&Oacute;N</u></strong><br>
                                <strong>&ldquo;<u>ADHERITE AL @RESUMEN CARTA</u>&rdquo;<u></u></strong><br>
  &nbsp;</p>
                          <ol>
                            <li class="gris2">CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. (EN ADELANTE, EL &ldquo;ORGANIZADOR&rdquo;) &ndash; INSCRIP. I.G.J. N&deg; 1323, L. 4, SOCIEDADES POR ACCIONES. CUIT  30-70181085-2, ORGANIZA LA PROMOCI&Oacute;N &ldquo;SORTEO LED TV E-RESUMEN&rdquo; (EN ADELANTE, LA &ldquo;PROMOCI&Oacute;N&rdquo;), CON ARREGLO A LAS SIGUIENTES BASES Y CONDICIONES (EN ADELANTE, LAS &ldquo;BASES&rdquo;). LA FORMA DE PARTICIPACI&Oacute;N EN LA PRESENTE PROMOCI&Oacute;N, DE ACCEDER A LOS PREMIOS &ndash; CONFORME SE DEFINE ESTE T&Eacute;RMINO M&Aacute;S ADELANTE - Y RESTANTES CONDICIONES SE ENCUENTRAN CONTENIDAS EN LAS PRESENTES BASES LAS CUALES SE ENCUENTRAN DISPONIBLES EN LOS LOCALES DE ATENCI&Oacute;N AL P&Uacute;BLICO DEL ORGANIZADOR UBICADOS DENTRO DE LAS SUCURSALES DE CARTA AUTOM&Aacute;TICA UBICADAS EN SAN MART&Iacute;N 945, COMODORO RIVADAVIA. G&Uuml;EMES 41, CALETA OLIVIA. IRIGOYEN 371, CIPOLLETI. C.H. RODR&Iacute;GUEZ 176, CUTRAL C&Oacute;. TUCUM&Aacute;N 645, GRAL. ROCA. ALCORTA 151, NEUQU&Eacute;N. SAN MART&Iacute;N 226 (LOCAL 5), PUERTO MADRYN. SAN MART&Iacute;N 139, BAH&Iacute;A BLANCA. B. IRIGOYEN 389, PUNTA ALTA. 9 DE JULIO 128, TRELEW. 9 DE JULIO 391, CHOELE CHOEL. SAN MART&Iacute;N 89, VILLA REGINA. 25 DE MAYO 455, VIEDMA. KIRCHNER (EX ROCA) 1085, R&Iacute;O GALLEGOS. CONGRESO 69, TUCUM&Aacute;N. ONELLI 754, BARILOCHE. AVELLANEDA 166, SANTA ROSA. CALLE 51 N&ordf; 674, LA PLATA. PERITO MORENO 265, R&Iacute;O GRANDE (EN ADELANTE TODOS EN CONJUNTO LOS &ldquo;LOCALES DE ATENCI&Oacute;N&rdquo;) Y EN EL SITIO WEB WWW.CORDIALFINANCIERA.COM.AR (EL &ldquo;SITIO&rdquo;).</li>
<li class="gris2">LA PROMOCI&Oacute;N TENDR&Aacute; VIGENCIA ENTRE LAS 00 HS. DEL D&Iacute;A 01/10/2016 Y LAS 24 HS. DEL D&Iacute;A 31/12/2016 Y SER&Aacute; V&Aacute;LIDA EN LAS CIUDADES DE COMODORO RIVADAVIA, CALETA OLIVIA, CIPOLLETI, CUTRAL C&Oacute;, GRAL. ROCA, NEUQU&Eacute;N, PUERTO MADRYN, BAH&Iacute;A BLANCA, PUNTA ALTA, TRELEW, CHOELE CHOEL, VILLA REGINA, VIEDMA, RIO GALLEGOS, TUCUM&Aacute;N, BARILOCHE, SANTA ROSA, LA PLATA Y R&Iacute;O GRANDE. PODR&Aacute;N PARTICIPAR EN LA PROMOCI&Oacute;N LAS PERSONAS F&Iacute;SICAS MAYORES DE 18 A&Ntilde;OS SIN OBLIGACI&Oacute;N DE COMPRA ALGUNA (EN ADELANTE EL/OS PARTICIPANTE/S), Y EN LA MEDIDA QUE CUMPLAN CON LAS CONDICIONES ESTIPULADAS EN LAS PRESENTES BASES. LOS PARTICIPANTES NO DEBER&Aacute;N REGISTRAR EMBARGOS, INHIBICIONES, NI DEUDAS EN CUALQUIERA DE LOS PRODUCTOS QUE TUVIERAN CONTRATADOS O CONTRATAREN CON EL ORGANIZADOR DURANTE LA VIGENCIA DE LA PROMOCI&Oacute;N. </li>
<li class="gris2">LOS PARTICIPANTES DEBER&Aacute;N ADHERIRSE Y SOLICITAR EL RESUMEN DIGITAL (EL &ldquo;RESUMEN DIGITAL&rdquo;) DE SU TARJETA DE CR&Eacute;DITO CARTA MASTERCARD EMITIDA POR CORDIAL. LOS PARTICIPANTES NO DEBER&Aacute;N REGISTRAR EMBARGOS, INHIBICIONES, NI DEUDAS EN CUALQUIERA DE LOS PRODUCTOS QUE TUVIERAN CONTRATADOS O CONTRATAREN CON EL ORGANIZADOR DURANTE TODA LA VIGENCIA DE LA PROMOCI&Oacute;N. <br />
ASIMISMO LOS PARTICIPANTES QUE SE HAYAN ADHERIDO AL RESUMEN DIGITAL Y QUE HAYAN DESCARGADO O DESCARGUEN LA APLICACI&Oacute;N DENOMINADA CARTAAPP Y SE LOGUEN AL MENOS UNA VEZ DURANTE LA VIGENCIA DE LA PROMOCI&Oacute;N, OBTENDR&Aacute;N OTRA CHANCE DE PARTICIPACI&Oacute;N.</li>
<li class="gris2">LA PROMOCI&Oacute;N ES SIN OBLIGACI&Oacute;N DE COMPRA, LAS PERSONAS F&Iacute;SICAS MAYORES DE 18 A&Ntilde;OS QUE NO CUMPLAN CON LOS REQUISITOS DETALLADOS EN LA CL&Aacute;USULA 4) PRECEDENTE, PODR&Aacute;N PARTICIPAR DE LA PROMOCI&Oacute;N, ENVIANDO UN SOBRE CERRADO, EN CUYO FRENTE ESCRIBIR&Aacute;N   &ldquo;SORTEO LED TV E-RESUMEN&rdquo;, A CUALQUIERA DE LOS LOCALES DE ATENCI&Oacute;N, EN EL HORARIO DE 9 HS. A 17 HS. Y DE LUNES A VIERNES, 1 (UN) DIBUJO DEL ISOLOGO DEL ORGANIZADOR (NO SE ACEPTAR&Aacute;N FOTOCOPIAS NI OTRO TIPO DE REPRODUCCIONES) HECHO A MANO ALZADA, EN COLORES Y CON LAS SIGUIENTES DIMENSIONES: ANCHO: 25CM. ALTO: 20CM. AL DORSO DEL DIBUJO DEBER&Aacute;N INDICARSE LOS SIGUIENTES DATOS DEL PARTICIPANTE EN LETRA CLARA Y LEGIBLE: NOMBRES Y APELLIDO, N&Uacute;MERO Y TIPO DE DOCUMENTO DE IDENTIDAD, DOMICILIO PARTICULAR, TEL&Eacute;FONO, FECHA DE NACIMIENTO Y DIRECCI&Oacute;N DE E-MAIL. RECIBIDO EL SOBRE Y COMPROBADO QUE SE CUMPLEN TODOS LOS REQUISITOS EXIGIDOS, EL MISMO PARTICIPAR&Aacute; DEL SORTEO. SE RECIBIR&Aacute;N SOBRES HASTA LAS 24 HS. DEL D&Iacute;A 31/12/2016.</li>
<li class="gris2">LOS PREMIOS OBJETO DE LA PROMOCI&Oacute;N EN ADELANTE (EL &ldquo;PREMIO&rdquo; O LOS &ldquo;PREMIOS&rdquo;) SEG&Uacute;N CORRESPONDA, CONSISTIR&Aacute;N EN TRES (3) TELEVISORES LED DE 43 PULGADAS; MARCA PHILIPS; MODELO 43PFG5501. </li>
<li class="gris2">LOS PARTICIPANTES QUE HUBIEREN FORMADO PARTE DE LA PROMOCI&Oacute;N, PARTICIPAR&Aacute;N EN LOS SORTEOS A REALIZARSE ANTE ESCRIBANO P&Uacute;BLICO EN LA SUCURSAL DEL ORGANIZADOR SITA EN JUAN BAUTISTA DE LASALLE 653, CIUDAD DE BUENOS AIRES, PCIA. DE BUENOS AIRES Y CONFORME SE DETALLA SEGUIDAMENTE. SE REALIZAR&Aacute; UN SORTEO POR MES, Y SE CORRESPONDER&Aacute; CON LAS ADHESIONES AL RESUMEN DIGITAL QUE SE HUBIERAN REALIZADO DURANTE EL MES AL QUE CORRESPONDE EL SORTEO. EN CADA SORTEO SE SORTEAR&Aacute; UN PREMIO. LOS SORTEOS SER&Aacute;N REALIZADOS A LAS 16 HS., EN LAS SIGUIENTES FECHAS: (I) ADHESIONES DEL MES DE OCTUBRE &ndash; EL D&Iacute;A 14/11/2016 (II) ADHESIONES DEL MES DE NOVIEMBRE - EL D&Iacute;A 12/12/2016; (III) ADHESIONES DEL MES DE DICIEMBRE &ndash; EL D&Iacute;A 16/01/2017. CADA SORTEO SE LLEVAR&Aacute; A CABO DE LA SIGUIENTE MANERA: EN FORMA ELECTR&Oacute;NICA SE ASIGNAR&Aacute; UN N&Uacute;MERO SECUENCIAL CORRELATIVO DE PARTICIPACI&Oacute;N A LOS DATOS DE LOS PARTICIPANTES Y DE ACUERDO A LA CANTIDAD DE CHANCES OBTENIDAS. EN FORMA ELECTR&Oacute;NICA SE SELECCIONAR&Aacute; 1 (UN) N&Uacute;MERO AL AZAR POR CADA PREMIO SORTEADO, QUE SE CORRESPONDER&Aacute; CON EL NOMBRE DEL PARTICIPANTE QUIEN SE CONSTITUIR&Aacute; EN EL POTENCIAL GANADOR (EL POTENCIAL GANADOR). EL MISMO PROCEDIMIENTO SE APLICAR&Aacute; PARA SELECCIONAR 1 (UN) POTENCIAL GANADOR SUPLENTE POR CADA PREMIO SORTEADO (EL POTENCIAL GANADOR SUPLENTE) PARA EL CASO QUE POR CUALQUIER CAUSA NO SE PUDIERAN ADJUDICAR EL PREMIO AL POTENCIAL GANADOR. EN TAL SENTIDO, DE VERIFICARSE LA IMPOSIBILIDAD DE ADJUDICAR EL PREMIO POR CAUSAS NO IMPUTABLES AL ORGANIZADOR, SE FAVORECER&Aacute; CON EL PREMIO NO ASIGNADO AL PARTICIPANTE CUYO NOMBRE HUBIERA SIDO SORTEADO COMO GANADOR SUPLENTE. </li>
<li class="gris2">LA PROBABILIDAD MATEM&Aacute;TICA DE ADJUDICACI&Oacute;N DEL PREMIO DEPENDER&Aacute; DE LA CANTIDAD DE PARTICIPANTES. TOMANDO EN CONSIDERACI&Oacute;N SI PARTICIPARAN 100 PERSONAS, LA PROBABILIDAD DE GANAR SER&Iacute;A DE 1% POR CADA PARTICIPANTE. CABE DESTACAR QUE LA PROBABILIDAD MATEM&Aacute;TICA INFORMADA ES MERAMENTE ILUSTRATIVA Y ESTIMATIVA DEBIDO A QUE NO SE PUEDEN CONOCER QU&Eacute; CANTIDAD EXACTA DE PARTICIPANTES.</li>
<li class="gris2">LA ASIGNACI&Oacute;N DE LOS PREMIOS, SER&Aacute; NOTIFICADO A CADA POTENCIAL GANADOR - DENTRO DE LOS 7 (SIETE) D&Iacute;AS POSTERIORES DE HABERSE REALIZADO EL SORTEO ANTE ESCRIBANO P&Uacute;BLICO - POR UN MEDIO DE NOTIFICACI&Oacute;N FEHACIENTE (A DEFINIR POR EL ORGANIZADOR) AL DOMICILIO QUE HUBIERE INFORMADO EN EL CUP&Oacute;N. ASIMISMO EL ORGANIZADOR PODR&Aacute; OPTAR A SU VEZ POR OTROS MEDIOS ADICIONALES ALTERNATIVOS DE NOTIFICACI&Oacute;N COMO SER UN LLAMADO TELEF&Oacute;NICO O LA REMISI&Oacute;N DE UN MAIL A LA DIRECCI&Oacute;N DE MAIL O TEL&Eacute;FONO QUE EL POTENCIAL GANADOR HUBIERA INFORMADO EN EL CUP&Oacute;N. EL POTENCIAL GANADOR DEBER&Aacute; PRESENTARSE CON SU DOCUMENTO DE IDENTIDAD, EN UN PLAZO NO MAYOR A 30 (TREINTA) D&Iacute;AS CORRIDOS POSTERIORES A LA FECHA DE REALIZACI&Oacute;N DEL SORTEO, EN LA SEDE DEL ORGANIZADOR SITA EN JUAN BAUTISTA DE LASALLE 653, CIUDAD DE BUENOS AIRES, PCIA. DE BUENOS AIRES &ndash;, EN EL HORARIO DE 9 HS. A 17 HS- O EN CASO DE POSEER SU DOMICILIO A M&Aacute;S DE 50 KM. DE LA MISMA, DEBER&Aacute; ACERCARSE A LA SUCURSAL DEL ORGANIZADOR M&Aacute;S CERCANA A SU DOMICILIO EN EL HORARIO DE 9 HS. A 17 HS. EL ORGANIZADOR SE RESERVA EL DERECHO DE ENTREGA DEL PREMIO, &Oacute; INSTRUMENTO QUE DISPONGA LA PUESTA A DISPOSICI&Oacute;N DEL MISMO, HASTA EL PLAZO DE 30 (TREINTA) D&Iacute;AS CORRIDOS POSTERIORES A HABERSE REALIZADO EL SORTEO. EL DERECHO A LA ASIGNACI&Oacute;N DEL PREMIO, ESTAR&Aacute; CONDICIONADA A QUE EL POTENCIAL GANADOR CONTESTE CORRECTAMENTE DOS (2) PREGUNTAS DE CULTURA GENERAL QUE SE LE FORMULAR&Aacute;N. SI EL POTENCIAL GANADOR NO CONTESTARA CORRECTAMENTE LAS DOS (2) PREGUNTAS, SE NOTIFICAR&Aacute; AL POTENCIAL GANADOR SUPLENTE. LAS PREGUNTAS SE ENCONTRAR&Aacute;N EN UN SOBRE CERRADO.. LA FALTA DE PRESENTACI&Oacute;N EN EL TIEMPO Y FORMA INDICADA Y/O LA CONTESTACI&Oacute;N INCORRECTA DE LAS PREGUNTAS DE CULTURA GENERAL, HAR&Aacute;N PERDER AL POTENCIAL GANADOR EL DERECHO A ASIGNACI&Oacute;N DEL PREMIO. </li>
<li class="gris2">EL ORGANIZADOR NO SE HAR&Aacute; RESPONSABLE DE GASTOS DE TRASLADOS NI DE NING&Uacute;N GASTO EN QUE DEBA INCURRIRSE PARA RETIRAR EL PREMIO NI DE LOS GASTOS QUE SE GENEREN CON POSTERIORIDAD A LA ENTREGA DEL MISMO.</li>
<li class="gris2">LA RESPONSABILIDAD DEL ORGANIZADOR POR TODO CONCEPTO FINALIZA CON LA PUESTA A DISPOSICI&Oacute;N DEL GANADOR DEL PREMIO. </li>
<li class="gris2">LA PARTICIPACI&Oacute;N EN LA PROMOCI&Oacute;N, EST&Aacute; SUJETA A T&Eacute;RMINOS, CONDICIONES, REGLAMENTOS, DISPOSICIONES, POL&Iacute;TICAS Y PROCEDIMIENTOS ESTABLECIDOS POR EL ORGANIZADOR. TODO ABUSO DE LOS DERECHOS DEL MISMO, TODA CONDUCTA CONTRARIA DE LOS PARTICIPANTES -EN FORMA INDIVIDUAL O COLECTIVA- EN DETRIMENTO DE LOS INTERESES DEL ORGANIZADOR PODR&Aacute; RESULTAR EN LA ANULACI&Oacute;N DEL PREMIO. </li>
<li class="gris2">TODA DIVERGENCIA QUE PUDIERA SURGIR CON RELACI&Oacute;N A LA PROMOCI&Oacute;N Y A TODOS LOS EFECTOS DE LA MISMA, LAS PARTES (CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. Y LOS PARTICIPANTES), SE SOMETEN A LA JURISDICCI&Oacute;N Y COMPETENCIA DE LOS TRIBUNALES ORDINARIOS EN LO COMERCIAL DE LA CIUDAD AUT&Oacute;NOMA DE BUENOS AIRES, RENUNCIANDO A CUALQUIER OTRO FUERO QUE LES PUDIERA CORRESPONDER.</li>
<li class="gris2">EL HECHO DE ACEPTAR EL PREMIO IMPLICA PARA EL GANADOR LA AUTORIZACI&Oacute;N T&Aacute;CITA A ORGANIZADOR PARA DIFUNDIR O PUBLICAR SUS NOMBRES Y/O DIVULGAR SUS IM&Aacute;GENES, Y/O DIVULGAR SUS FOTOGRAF&Iacute;AS Y/O DIVULGAR SU VOZ CON FINES PUBLICITARIOS EN LOS MEDIOS Y EN LAS FORMAS QUE CONSIDERE CORRECTAS, SIN DERECHO DE COMPENSACI&Oacute;N ALGUNA DURANTE EL TRANSCURSO DE LA PROMOCI&Oacute;N Y HASTA UN A&Ntilde;O DESPU&Eacute;S DEL INICIO DE LA PROMOCI&Oacute;N.</li>
<li class="gris2">EL PARTICIPANTE PRESTA SU CONSENTIMIENTO, CONFORME LOS T&Eacute;RMINOS DE LA LEY 25.326 DE PROTECCI&Oacute;N DE DATOS PERSONALES, PARA QUE EL ORGANIZADOR PUEDA UTILIZAR Y/O DISPONER Y/O CEDER LA INFORMACI&Oacute;N QUE LE HA SUMINISTRADO, MANTENIENDO LA CONFIDENCIALIDAD Y SEGURIDAD DE LOS DATOS &ndash; A SUS AFILIADAS, SUBSIDIRIAS Y/O TERCEROS, YA SEA CON FINES COMERCIALES COMO ESTAD&Iacute;STICOS. ASIMISMO EL PARTICIPANTE MANIFIESTA EXPRESAMENTE CONOCER QUE PUEDE EJERCER LOS DERECHOS DE ACCESO, RECTIFICACI&Oacute;N Y SUPRESI&Oacute;N DE LA INFORMACI&Oacute;N, CONFORME LA LEGISLACI&Oacute;N APLICABLE.</li>
<li class="gris2">NO PODR&Aacute;N PARTICIPAR EN LA PROMOCI&Oacute;N EL PERSONAL DE CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A., NI DEL GRUPO SUPERVIELLE S.A., NI DE NINGUNA DE LAS EMPRESAS QUE FORMAN PARTE INTEGRANTE DEL GRUPO SUPERVIELLE S.A., NI SUS AGENCIAS DE PUBLICIDAD Y/O PROMOCI&Oacute;N, NI TAMPOCO SUS FAMILIARES DIRECTOS HASTA EL SEGUNDO GRADO DE CONSANGUINIDAD DE LOS NOMBRADOS COMO AS&Iacute; TAMPOCO SUS FAMILIARES HASTA SEGUNDO GRADO. </li>
<li class="gris2">LA BOLSA DE PREMIOS PARA EL PRESENTE SORTEO HA SIDO FIJADA EN LA SUMA DE PESOS $ 35.100 (PESOS TREINTA Y CINCO MIL CIEN).</li>
</ol>
                             </td>
                          </tr>
                          <tr><td><p>&nbsp;</p></td></tr>
                          <tr>
                            <td align="center"><img src="images/ganadores-digitalizate.jpg"></td>
                          </tr>
                          <tr>
                            <td align="left" class="gris2" id="bienvenida">&nbsp;</td>
                          </tr>
                          <tr>
                            <td align="left"> <p align="left" class="gris2"><strong><u>BASES PROMOCI&Oacute;N</u></strong><br>
                                <strong>&ldquo;<u>DIGITALIZATE Y GAN&Aacute;</u>&rdquo;<u></u></strong><br>
  &nbsp;</p>
                          <ol>
                            <li class="gris2">CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. (EN ADELANTE, EL &ldquo;ORGANIZADOR&rdquo;) &ndash; INSCRIP. I.G.J. N&deg; 1323, L. 4, SOCIEDADES POR ACCIONES. CUIT N&ordm; 30-70181085-2., ORGANIZA LA PROMOCI&Oacute;N &rdquo;BAJATELA Y PARTICIP&Aacute;&rdquo;. (EN ADELANTE, LA &ldquo;PROMOCI&Oacute;N&rdquo;), CON ARREGLO A LAS SIGUIENTES BASES Y CONDICIONES (EN ADELANTE, LAS &ldquo;BASES&rdquo;).</li>
<li class="gris2">LA FORMA DE PARTICIPACI&Oacute;N EN LA PRESENTE PROMOCI&Oacute;N, DE ACCEDER A LOS PREMIOS &ndash; CONFORME SE DEFINE ESTE T&Eacute;RMINO M&Aacute;S ADELANTE - Y RESTANTES CONDICIONES SE ENCUENTRAN CONTENIDAS EN LAS PRESENTES BASES LAS CUALES SE ENCUENTRAN DISPONIBLES EN LOS LOCALES DE ATENCI&Oacute;N AL P&Uacute;BLICO DEL ORGANIZADOR UBICADOS DENTRO DE LAS SUCURSALES DE TARJETA AUTOM&Aacute;TICA S.A. UBICADAS EN LAS CIUDADES DE COMODORO RIVADAVIA, TUCUM&Aacute;N, CALETA OLIVIA, CIPOLLETI, VILLA REGINA, CUTRAL C&Oacute;, GRAL. ROCA, NEUQU&Eacute;N, PUERTO MADRYN, BAH&Iacute;A BLANCA, PUNTA ALTA, TRELEW, CHOELE CHOEL, BARILOCHE, SANTA ROSA, LA PLATA, R&Iacute;O GRANDE, VIEDMA, Y R&Iacute;O GALLEGOS. (EN ADELANTE TODOS EN CONJUNTO LOS &ldquo;LOCALES DE ATENCI&Oacute;N&rdquo;) Y EN EL SITIO WEB WWW.CORDIALFINANCIERA.COM.AR (EL &ldquo;SITIO&rdquo;)</li>
<li class="gris2">A PROMOCI&Oacute;N TENDR&Aacute; VIGENCIA ENTRE LAS 00 HS. DEL D&Iacute;A 01 DE JUNIO DE 2016 Y LAS 24 HS. DEL D&Iacute;A 31 DE JULIO DE 2016 Y SER&Aacute; V&Aacute;LIDA EN LAS CIUDADES DE COMODORO RIVADAVIA, TUCUM&Aacute;N, CALETA OLIVIA, CIPOLLETI, VILLA REGINA, CUTRAL C&Oacute;, GRAL. ROCA, NEUQU&Eacute;N, PUERTO MADRYN, BAH&Iacute;A BLANCA, PUNTA ALTA, TRELEW, CHOELE CHOEL, BARILOCHE, SANTA ROSA, LA PLATA, R&Iacute;O GRANDE, VIEDMA, Y R&Iacute;O GALLEGOS. </li>
<li class="gris2">LA PRESENTE PROMOCI&Oacute;N ES SIN OBLIGACI&Oacute;N DE COMPRA. PODR&Aacute;N PARTICIPAR DE LA PROMOCI&Oacute;N TODAS LAS PERSONAS F&Iacute;SICAS MAYORES DE 18 A&Ntilde;OS Y QUE CUMPLAN CON LAS CONDICIONES ESTIPULADAS EN LAS PRESENTES BASES (LOS PARTICIPANTES). LOS PARTICIPANTES DESDE LA FECHA DE INICIO DE LA PROMOCI&Oacute;N, DURANTE SU VIGENCIA, Y HASTA LA FECHA DE ENTREGA DE LOS PREMIOS NO PODR&Aacute;N REGISTRAR EMBARGOS, INHIBICIONES, NI DEUDAS ANTE EL ORGANIZADOR. LOS PARTICIPANTES, PODR&Aacute;N PARTICIPACI&Oacute;N EN LA PROMOCI&Oacute;N  CONFORME SE DETALLA SEGUIDAMENTE EN LAS CL&Aacute;USULAS 5) Y 6).</li>
<li class="gris2">PARTICIPAN DE LA PROMOCI&Oacute;N AQUELLOS LOS CLIENTES TITULARES DE TARJETAS DE CR&Eacute;DITO CARTA MASTERCARD EMITIDAS POR EL ORGANIZADOR, QUE ACCEDAN DURANTE LA VIGENCIA DE LA PROMOCI&Oacute;N, POR PRIMERA VEZ A LA APLICACI&Oacute;N DISPONIBLE PARA SMARTPHONES O TABLES CON SISTEMA ANDROID DENOMINADA &ldquo;CARTA APP&rdquo; (LA &ldquo;APLICACI&Oacute;N&rdquo;). </li>
<li class="gris2">LA PROMOCI&Oacute;N ES SIN OBLIGACI&Oacute;N DE COMPRA, LAS PERSONAS F&Iacute;SICAS MAYORES DE 18 A&Ntilde;OS QUE NO CUMPLAN CON LOS REQUISITOS DETALLADOS EN LA CL&Aacute;USULA 5) PRECEDENTE, PODR&Aacute;N PARTICIPAR DE LA PROMOCI&Oacute;N, ENVIANDO UN SOBRE CERRADO, EN CUYO FRENTE ESCRIBIR&Aacute;N &ldquo;PROMOCI&Oacute;N &rdquo;BAJATELA Y PARTICIP&Aacute;&rdquo;, A LAS OFICINAS DEL ORGANIZADOR EN EL HORARIO DE 9 HS. A 17 HS. Y DE LUNES A VIERNES, 1 (UN) DIBUJO DEL ISOLOGO DEL ORGANIZADOR (NO SE ACEPTAR&Aacute;N FOTOCOPIAS NI OTRO TIPO DE REPRODUCCIONES) HECHO A MANO ALZADA, EN COLORES Y CON LAS SIGUIENTES DIMENSIONES: ANCHO: 25CM. ALTO: 20CM. AL DORSO DEL DIBUJO DEBER&Aacute;N INDICARSE LOS SIGUIENTES DATOS DEL PARTICIPANTE EN LETRA CLARA Y LEGIBLE: NOMBRES Y APELLIDO, N&Uacute;MERO Y TIPO DE DOCUMENTO DE IDENTIDAD, DOMICILIO PARTICULAR, TEL&Eacute;FONO, FECHA DE NACIMIENTO Y DIRECCI&Oacute;N DE E-MAIL. RECIBIDO EL SOBRE Y COMPROBADO QUE SE CUMPLEN TODOS LOS REQUISITOS EXIGIDOS, EL MISMO PARTICIPAR&Aacute; DEL SORTEO. SE RECIBIR&Aacute;N SOBRES HASTA LAS 17 HS. DEL D&Iacute;A 30 DE JULIO DE 2016. </li>
<li class="gris2">LOS PREMIOS (LOS &ldquo;PREMIOS&rdquo; EN CONJUNTO Y EN FORMA INDIVIDUAL EL &ldquo;PREMIO&rdquo;) CONSISTIR&Aacute;N EN:</li>
<li class="gris2">6 (SEIS) TABLETS MARCA ADMIRAL, DE 7 PULGADAS, (LAS &ldquo;TABLETS&rdquo;&rdquo; EN CONJUNTO Y LA &ldquo;TABLET&rdquo; EN FORMA INDIVIDUAL) </li>
<li class="gris2">LOS PREMIOS SON PERSONALES, E INTRANSFERIBLES Y NO PODR&Aacute;N CANJEARSE POR SU VALOR EN DINERO O POR OTROS BIENES, NI PODR&Aacute;N MODIFICARSE. </li>
<li class="gris2"> A LOS FINES DE DETERMINAR EL GANADOR DE CADA PREMIO, SE REALIZAR&Aacute;N SORTEOS ENTRE TODOS LOS PARTICIPANTES - CONFORME SE DEFINEN EN LAS CL&Aacute;USULAS 5) Y 6)- Y DE ACUERDO SE DETALLA A CONTINUACI&Oacute;N. TODOS LOS SORTEOS SE REALIZAR&Aacute;N EN LAS OFICINAS DEL ORGANIZADOR EN JUAN B. DE LASALLE 653, 1ER PISO SAN ISIDRO. BS. AS.
<br />(I) PARTICIPAR&Aacute;N DEL PRIMER SORTEO LOS PARTICIPANTES QUE HUBIERAN INGRESADO POR PRIMERA VEZ A LA APLICACI&Oacute;N DESDE EL D&Iacute;A 1 DE JUNIO DE 2016 Y EL 30 DE JUNIO DE 2016 INCLUSIVE. EL SORTEO SE REALIZAR&Aacute; EL D&Iacute;A 5 DEL MES DE JULIO DE 2016 A LAS 15 HS. SE SORTEAR&Aacute;N 3 (TRES) TABLETS.
<br />(II) PARTICIPAR&Aacute;N DEL SEGUNDO SORTEO LOS PARTICIPANTES QUE HUBIERAN INGRESADO POR PRIMERA VEZ A LA APLICACI&Oacute;N DESDE EL D&Iacute;A 1 DE JULIO DE 2016 Y EL 31 DE JULIO DE 2016 INCLUSIVE. EL SORTEO SE REALIZAR&Aacute; EL D&Iacute;A 5 DEL MES DE AGOSTO DE 2016 A LAS 15 HS. SE SORTEAR&Aacute;N 3 (TRES) TABLETS.
<br />TODOS LOS SORTEOS SE REALIZAR&Aacute;N ANTE ESCRIBANO P&Uacute;BLICO.
<br />ASIMISMO SI CUALQUIERA DE LOS SORTEOS NO PUDIERA SER REALIZADO EN LAS FECHAS INDICADAS PRECEDENTEMENTE POR FACTORES AJENOS A LA VOLUNTAD DEL ORGANIZADOR, COMO SER SIN LIMITACI&Oacute;N FERIADOS O D&Iacute;AS INH&Aacute;BILES, DICHO SORTEO SE REALIZAR&Aacute; EL PRIMER D&Iacute;A H&Aacute;BIL BANCARIO POSTERIOR.</li>
<li class="gris2">CADA SORTEO SE LLEVAR&Aacute; A CABO DE LA SIGUIENTE MANERA: EN FORMA ELECTR&Oacute;NICA SE ASIGNAR&Aacute; UN N&Uacute;MERO SECUENCIAL CORRELATIVO DE PARTICIPACI&Oacute;N A LOS DATOS DE LOS PARTICIPANTES QUE HUBIERAN INGRESADO A LA APLICACI&Oacute;N POR PRIMERA VEZ. EN FORMA ELECTR&Oacute;NICA SE SELECCIONAR&Aacute; 1 (UN) N&Uacute;MERO AL AZAR POR CADA PREMIO SORTEADO, QUE SE CORRESPONDER&Aacute; CON EL NOMBRE DEL PARTICIPANTE QUIEN SE CONSTITUIR&Aacute; EN EL POTENCIAL GANADOR (EL POTENCIAL GANADOR). EL MISMO PROCEDIMIENTO SE APLICAR&Aacute; PARA SELECCIONAR 1 (UN) POTENCIAL GANADOR SUPLENTE POR CADA PREMIO SORTEADO (EL POTENCIAL GANADOR SUPLENTE) PARA EL CASO QUE POR CUALQUIER CAUSA NO SE PUDIERAN ADJUDICAR EL PREMIO AL POTENCIAL GANADOR. EN TAL SENTIDO, DE VERIFICARSE LA IMPOSIBILIDAD DE ADJUDICAR EL PREMIO POR CAUSAS NO IMPUTABLES AL ORGANIZADOR, SE FAVORECER&Aacute; CON EL PREMIO NO ASIGNADO AL PARTICIPANTE CUYO NOMBRE HUBIERA SIDO SORTEADO COMO  GANADOR SUPLENTE. </li>
<li class="gris2">LA PROBABILIDAD MATEM&Aacute;TICA DE ADJUDICACI&Oacute;N DEL PREMIO DEPENDER&Aacute; DE LA CANTIDAD DE PARTICIPANTES. TOMANDO EN CONSIDERACI&Oacute;N SI PARTICIPARAN 1.000 (UN MIL) PERSONAS  LA PROBABILIDAD DE GANAR SER&Iacute;A 1 % POR CADA PARTICIPANTE. CABE DESTACAR QUE LA PROBABILIDAD MATEM&Aacute;TICA INFORMADA ES MERAMENTE ILUSTRATIVA Y ESTIMATIVA DEBIDO A QUE NO SE PUEDEN CONOCER QUE CANTIDAD EXACTA DE PARTICIPANTES.</li>
<li class="gris2">LA ASIGNACI&Oacute;N DEL PREMIO, SER&Aacute; NOTIFICADO AL POTENCIAL GANADOR - DENTRO DE LOS 7 (SIETE) D&Iacute;AS POSTERIORES DE HABERSE REALIZADO EL SORTEO ANTE ESCRIBANO P&Uacute;BLICO - POR UN MEDIO DE NOTIFICACI&Oacute;N FEHACIENTE (A DEFINIR POR EL ORGANIZADOR) AL DOMICILIO QUE HUBIERE DECLARADO ANTE EL ORGANIZADOR A LOS FINES DE CONTRATAR SUS PRODUCTOS.  ASIMISMO EL ORGANIZADOR PODR&Aacute; OPTAR A SU VEZ POR OTROS MEDIOS ADICIONALES ALTERNATIVOS DE NOTIFICACI&Oacute;N COMO SER UN LLAMADO TELEF&Oacute;NICO O LA REMISI&Oacute;N DE UN MAIL A LA DIRECCI&Oacute;N DE MAIL O TEL&Eacute;FONO QUE EL PARTICIPANTE TUVIERA REGISTRADOS EN EL ORGANIZADOR O A LOS QUE HUBIERA INFORMADO AL ORGANIZADOR AL MOMENTO DE REMITIR EL SOBRE (DE ACUERDO A LA CL&Aacute;USULA 6) EL POTENCIAL GANADOR DEBER&Aacute; PRESENTARSE CON SU DOCUMENTO DE IDENTIDAD, EN UN PLAZO NO MAYOR A 30 (TREINTA) D&Iacute;AS CORRIDOS POSTERIORES A LA FECHA DE REALIZACI&Oacute;N DEL SORTEO, EN LA SEDE DEL ORGANIZADOR SITA EN JUAN B. DE LASALLE 653, SAN ISIDRO, BS. AS., EN EL HORARIO DE 9 A 17 HS O EN CASO DE POSEER SU DOMICILIO A M&Aacute;S DE 50 KM. DE LA MISMA, DEBER&Aacute; ACERCARSE AL LOCAL DE ATENCI&Oacute;N M&Aacute;S CERCANO A SU DOMICILIO EN EL HORARIO DE 9 A 17 HS. EL ORGANIZADOR SE RESERVA EL DERECHO DE ENTREGA DEL PREMIO, &Oacute; INSTRUMENTO QUE DISPONGA LA PUESTA A DISPOSICI&Oacute;N DEL MISMO, HASTA EL PLAZO DE 30 (TREINTA) D&Iacute;AS CORRIDOS POSTERIORES A HABERSE REALIZADO EL SORTEO. EL DERECHO A LA ASIGNACI&Oacute;N DEL PREMIO, ESTAR&Aacute; CONDICIONADA A QUE EL POTENCIAL GANADOR CONTESTE CORRECTAMENTE DOS (2) PREGUNTAS DE CULTURA GENERAL QUE SE LE FORMULAR&Aacute;N. SI EL POTENCIAL GANADOR NO CONTESTARA CORRECTAMENTE LAS DOS (2) PREGUNTAS, SE NOTIFICAR&Aacute; AL POTENCIAL GANADOR SUPLENTE Y AS&Iacute; SUCESIVAMENTE, QUIENES EN TAL CASO SE CONSTITUIR&Aacute;N EN POTENCIAL GANADOR. LAS PREGUNTAS SE ENCONTRAR&Aacute;N EN UN SOBRE CERRADO EN PODER DE UN ESCRIBANO P&Uacute;BLICO. LA FALTA DE PRESENTACI&Oacute;N EN EL TIEMPO Y FORMA INDICADA Y/O LA CONTESTACI&Oacute;N INCORRECTA DE LAS PREGUNTAS DE CULTURA GENERAL, HAR&Aacute;N PERDER AL POTENCIAL GANADOR EL DERECHO A ASIGNACI&Oacute;N DEL PREMIO. A LOS FINES DE LA PROMOCI&Oacute;N SER&Aacute;N V&Aacute;LIDAS TODAS LAS NOTIFICACIONES REALIZADAS POR EL ORGANIZADOR EN EL DOMICILIO DEL POTENCIAL GANADOR QUE TENGA REGISTRADO AL MOMENTO DE PARTICIPAR, SALVO QUE &Eacute;STOS HUBIERAN INFORMADO POR ESCRITO AL ORGANIZADOR UNO DISTINTO.</li>
<li class="gris2">EL ORGANIZADOR NO SE HAR&Aacute; RESPONSABLE DE GASTOS DE TRASLADOS NI DE NING&Uacute;N GASTO EN QUE DEBA INCURRIRSE PARA RETIRAR EL PREMIO NI DE LOS GASTOS QUE SE GENEREN CON POSTERIORIDAD A LA ENTREGA DEL MISMO.</li>
<li class="gris2">LA RESPONSABILIDAD DE CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. POR TODO CONCEPTO FINALIZA CON LA PUESTA A DISPOSICI&Oacute;N DEL GANADOR DEL PREMIO. </li>
<li class="gris2">LA PARTICIPACI&Oacute;N EN LA PROMOCI&Oacute;N, EST&Aacute; SUJETA A T&Eacute;RMINOS, CONDICIONES, REGLAMENTOS, DISPOSICIONES, POL&Iacute;TICAS Y PROCEDIMIENTOS ESTABLECIDOS POR CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. TODO ABUSO DE LOS DERECHOS DEL MISMO, TODA CONDUCTA CONTRARIA DE LOS PARTICIPANTES -EN FORMA INDIVIDUAL O COLECTIVA- EN DETRIMENTO DE LOS INTERESES DE CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. PODR&Aacute; RESULTAR EN LA ANULACI&Oacute;N DEL PREMIO. </li>
<li class="gris2">TODA DIVERGENCIA QUE PUDIERA SURGIR CON RELACI&Oacute;N A LA PROMOCI&Oacute;N Y A TODOS LOS EFECTOS DE LA MISMA, LAS PARTES (CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. Y LOS PARTICIPANTES), SE SOMETEN A LA JURISDICCI&Oacute;N Y COMPETENCIA DE LOS TRIBUNALES ORDINARIOS EN LO COMERCIAL DE LA CIUDAD AUT&Oacute;NOMA DE BUENOS AIRES,  RENUNCIANDO A CUALQUIER OTRO FUERO QUE LES PUDIERA CORRESPONDER.</li>
<li class="gris2">EL HECHO DE ACEPTAR EL PREMIO IMPLICA PARA EL GANADOR LA AUTORIZACI&Oacute;N T&Aacute;CITA A CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A. PARA DIFUNDIR O PUBLICAR SUS NOMBRES Y/O DIVULGAR SUS IM&Aacute;GENES, Y/O DIVULGAR SUS FOTOGRAF&Iacute;AS Y/O DIVULGAR SU VOZ CON FINES PUBLICITARIOS EN LOS MEDIOS Y EN LAS FORMAS QUE CONSIDERE CORRECTAS, SIN DERECHO DE COMPENSACI&Oacute;N ALGUNA DURANTE EL TRANSCURSO DE LA PROMOCI&Oacute;N Y HASTA UN A&Ntilde;O DESPU&Eacute;S DEL INICIO DE LA PROMOCI&Oacute;N.</li>
<li class="gris2">EL PARTICIPANTE PRESTA SU CONSENTIMIENTO, CONFORME LOS T&Eacute;RMINOS DE LA LEY 25.326 DE PROTECCI&Oacute;N DE DATOS PERSONALES, PARA QUE EL ORGANIZADOR PUEDA UTILIZAR Y/O DISPONER Y/O CEDER LA INFORMACI&Oacute;N QUE LE HA SUMINISTRADO, MANTENIENDO LA CONFIDENCIALIDAD Y SEGURIDAD DE LOS DATOS &ndash; A SUS AFILIADAS, SUBSIDIRIAS Y/O TERCEROS, YA SEA CON FINES COMERCIALES COMO ESTAD&Iacute;STICOS. ASIMISMO EL PARTICIPANTE MANIFIESTA EXPRESAMENTE CONOCER QUE PUEDE EJERCER LOS DERECHOS DE ACCESO, RECTIFICACI&Oacute;N Y SUPRESI&Oacute;N DE LA INFORMACI&Oacute;N, CONFORME LA LEGISLACI&Oacute;N APLICABLE.</li>
<li class="gris2">NO PODR&Aacute;N PARTICIPAR EN LA PROMOCI&Oacute;N EL PERSONAL DE CORDIAL COMPA&Ntilde;&Iacute;A FINANCIERA S.A.., NI DEL GRUPO SUPERVIELLE S.A., NI DE NINGUNA DE LAS EMPRESAS QUE FORMAN PARTE INTEGRANTE DEL GRUPO SUPERVIELLE S.A. </li>
<li class="gris2">TODO ACTO U OPERACI&Oacute;N EJECUTADO POR EL PARTICIPANTE A TRAV&Eacute;S DE CUALQUIER DISPOSITIVO, QUE RESULTE CONTRARIO A LOS T&Eacute;RMINOS Y CONDICIONES DE &Eacute;STAS BASES, A&Uacute;N CUANDO EL SERVICIO HUBIERE ADMITIDO TAL ACTO U OPERACI&Oacute;N, PODR&Aacute; SER ANULADO POR EL ORGANIZADOR, SIN NECESIDAD DE PREAVISO ALGUNO, NI DERECHO RESARCITORIO NI COMPENSATORIO A FAVOR DEL PARTICIPANTE.</li>
<li class="gris2">LA BOLSA DE PREMIOS PARA EL PRESENTE SORTEO HA SIDO FIJADA EN LA SUMA DE PESOS $ 10.200 (PESOS DIEZ MIL DOSCIENTOS).</li>
</ol>
                             </td>
                          </tr>
                        </table></td>
                        <td width="1" height="1"></td>
                      </tr>
                      <tr>
                        <td width="1" height="1" ></td>
                        <td width="547" height="1" ></td>
                        <td width="1" height="1"></td>
                      </tr>
                    </table></td>
                  </tr>
                </table></td>
              </tr>
            </table></td>
          </tr>
        </table></td>
        <td width="9" background="images/right.gif">&nbsp;</td>
      </tr>
      <tr>
        <td height="9"><img src="images/corner_left.gif" alt="" width="9" height="9"></td>
        <td height="9" background="images/down.gif"><img src="images/down.gif" alt="" width="1" height="9"></td>
        <td height="9"><img src="images/corner_right.gif" alt="" width="9" height="9"></td>
      </tr>
    <tr>
      <td>&nbsp;</td>
      <td><table width="99%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="4%" height="10" align="center"><span class="estilo"><a href="http://www.iutopi.com" target="_blank" class="blanco" style="color: #666666">i</a></span></td>
          <td width="43%" align="right" style="color: #333333"><a href="#" class="blanco" style="color: #666" onMouseUp="MM_openBrWindow('acuerdo.htm','','scrollbars=yes,width=550,height=500')">Pol<span style="color: #666666"></span><span style="color: #999999"></span>&iacute;tica de Usuario</a></td>
          <td width="53%" align="left" class="blanco-1" style="color: #666666">- <a href="sitemap.asp" class="blanco" style="color: #666666">Mapa del Sitio</a> <span class="blanco1">- Todos los derechos reservados &copy; Carta Autom&aacute;tica 2013</span></td>
        </tr>
      </table></td>
    </tr>
  </table>
</body>
</html>